from typing import Any, Iterator, List, Optional, Tuple, Union

class BoundaryType:
    Inclusive: BoundaryType
    Exclusive: BoundaryType

class Interval:
    begin: float
    end: float
    data: Any
    start_inclusive: bool
    end_inclusive: bool

    def __init__(
        self,
        begin: float,
        end: float,
        data: Any = None,
        start_inclusive: Optional[bool] = None,
        end_inclusive: Optional[bool] = None,
    ) -> None: ...
    def overlaps(self, point: float) -> bool: ...
    def overlaps_range(self, start: float, end: float) -> bool: ...
    def overlaps_interval(self, other: Interval) -> bool: ...
    def enveloped_by(self, start: float, end: float) -> bool: ...
    def enveloped_by_interval(self, other: Interval) -> bool: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __getitem__(self, index: int) -> Any: ...
    def __len__(self) -> int: ...

class IntervalTree:
    start_inclusive: bool
    end_inclusive: bool

    def __init__(
        self,
        intervals: Optional[List[Interval]] = None,
        start_inclusive: bool = True,
        end_inclusive: bool = False,
    ) -> None: ...
    @classmethod
    def from_tuples(
        cls,
        tuples: List[Union[Tuple[float, float], Tuple[float, float, Any]]],
    ) -> IntervalTree: ...

    # Queries
    def at(self, point: float) -> List[Interval]: ...
    def overlap(self, start: float, end: float) -> List[Interval]: ...
    def envelop(self, start: float, end: float) -> List[Interval]: ...
    def overlaps(self, point_or_start: float, end: Optional[float] = None) -> bool: ...
    def items(self) -> List[Interval]: ...

    # Insertion
    def add(self, interval: Interval) -> None: ...
    def addi(self, begin: float, end: float, data: Any = None) -> None: ...

    # Deletion
    def remove(self, interval: Interval) -> None: ...
    def discard(self, interval: Interval) -> None: ...
    def removei(self, begin: float, end: float, data: Any = None) -> None: ...
    def discardi(self, begin: float, end: float, data: Any = None) -> None: ...
    def remove_overlap(self, point_or_start: float, end: Optional[float] = None) -> None: ...
    def remove_envelop(self, start: float, end: float) -> None: ...
    def clear(self) -> None: ...
    def pop(self) -> Interval: ...

    # Info
    def is_empty(self) -> bool: ...
    def begin(self) -> Optional[float]: ...
    def end(self) -> Optional[float]: ...
    def containsi(self, begin: float, end: float, data: Any = None) -> bool: ...

    # Set operations
    def union(self, other: IntervalTree) -> IntervalTree: ...
    def update(self, other: Union[IntervalTree, List[Interval]]) -> None: ...
    def difference(self, other: IntervalTree) -> IntervalTree: ...
    def difference_update(self, other: IntervalTree) -> None: ...
    def intersection(self, other: IntervalTree) -> IntervalTree: ...
    def intersection_update(self, other: IntervalTree) -> None: ...
    def symmetric_difference(self, other: IntervalTree) -> IntervalTree: ...
    def symmetric_difference_update(self, other: IntervalTree) -> None: ...
    def issubset(self, other: IntervalTree) -> bool: ...
    def issuperset(self, other: IntervalTree) -> bool: ...

    # Restructuring
    def chop(self, begin: float, end: float, datafunc: Any = None) -> None: ...
    def slice(self, point: float, datafunc: Any = None) -> None: ...
    def split_overlaps(self, datafunc: Any = None) -> None: ...
    def merge_overlaps(self, datafunc: Any = None, strict: Optional[bool] = True) -> None: ...
    def merge_equals(self, datafunc: Any = None) -> None: ...
    def merge_neighbors(self, datafunc: Any = None, max_dist: Optional[float] = None, merge_overlaps: Optional[bool] = None) -> None: ...

    # Copy
    def copy(self) -> IntervalTree: ...

    # Analysis
    def score(self, full_report: bool = False) -> Any: ...

    # Dunder methods
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, interval: Interval) -> bool: ...
    def __iter__(self) -> Iterator[Interval]: ...
    def __getitem__(self, index: Union[float, slice]) -> List[Interval]: ...
    def __setitem__(self, index: Union[float, slice], value: Any) -> None: ...
    def __delitem__(self, index: Union[float, slice]) -> None: ...
    def __or__(self, other: IntervalTree) -> IntervalTree: ...
    def __ior__(self, other: IntervalTree) -> IntervalTree: ...
    def __sub__(self, other: IntervalTree) -> IntervalTree: ...
    def __isub__(self, other: IntervalTree) -> IntervalTree: ...
    def __and__(self, other: IntervalTree) -> IntervalTree: ...
    def __iand__(self, other: IntervalTree) -> IntervalTree: ...
    def __xor__(self, other: IntervalTree) -> IntervalTree: ...
    def __ixor__(self, other: IntervalTree) -> IntervalTree: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __le__(self, other: IntervalTree) -> bool: ...
    def __ge__(self, other: IntervalTree) -> bool: ...
    def __lt__(self, other: IntervalTree) -> bool: ...
    def __gt__(self, other: IntervalTree) -> bool: ...
    def __repr__(self) -> str: ...
